//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int CommentID { get; set; }
        public int PhotoID { get; set; }
        public string Body { get; set; }
        public string ClientProfileID { get; set; }
    
        public virtual ClientProfiles ClientProfiles { get; set; }
        public virtual Photos Photos { get; set; }
    }
}
